# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:maledictus",
    "legendary_monsters:overgrown_colossus",
    "cataclysm:coral_golem",
    "born_in_chaos_v1:mother_spider",
    "zombie_island:walker_3",
    "zombie_island:walker_4",
    "born_in_chaos_v1:siamese_skeletonsleft",
    "zombie_island:walker_1",
    "zombie_island:walker_2",
    "zombie_island:eat_courier",
    "born_in_chaos_v1:siamese_skeletonsright",
    "minecraft:trader_llama",
    "apocalypsenow:soldiers_02",
    "minecraft:horse",
    "born_in_chaos_v1:lifestealer",
    "born_in_chaos_v1:riding_felsteed",
    "born_in_chaos_v1:pumpkin_bomb",
    "zombie_island:firefighter_walker",
    "minecraft:llama",
    "born_in_chaos_v1:skeleton_demoman",
    "zombie_extreme:goon",
    "graveyard:skeleton_creeper",
    "extinction:infected_police",
    "cataclysm:ender_guardian",
    "cataclysm:deepling_warlock",
    "minecraft:tadpole",
    "minecraft:dolphin",
    "zombie_extreme:devestated",
    "apocalypsenow:rat",
    "faded_conquest_2:blocknight_boot",
    "born_in_chaos_v1:supreme_bonescaller",
    "apocalypsenow:hunter",
    "born_in_chaos_v1:pumpkin_bruiser",
    "zombie_extreme:infected_military",
    "graveyard:nightmare",
    "faded_conquest_2:poisonspikea",
    "legendary_monsters:shulker_mimic",
    "legendary_monsters:haunted_knight",
    "faded_conquest_2:vessel_of_calamity",
    "zombie_island:grenadier_walker",
    "faded_conquest_2:calamity_spell",
    "extinction:runner",
    "zombie_extreme:divided",
    "minecraft:bee",
    "graveyard:reaper",
    "sona:sound_decoy",
    "minecraft:illusioner",
    "zombiesmore:explosive_zombie",
    "born_in_chaos_v1:dread_hound",
    "born_in_chaos_v1:skeleton_thrasher_not_despawn",
    "born_in_chaos_v1:baby_spider",
    "minecraft:mooshroom",
    "legendary_monsters:stratling",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "born_in_chaos_v1:seared_spirit_not_despawn",
    "faded_conquest_2:lich_phase_2",
    "minecraft:drowned",
    "born_in_chaos_v1:bone_imp_minion",
    "minecraft:axolotl",
    "zombie_extreme:faceless",
    "legendary_monsters:ambusher",
    "faded_conquest_2:faded_king",
    "born_in_chaos_v1:pumpkin_dunce",
    "zombie_extreme:revived",
    "zombie_island:insect_swarm_walker",
    "born_in_chaos_v1:senor_pumpkin",
    "born_in_chaos_v1:mrs_pumpkin",
    "apocalypsenow:horde_2",
    "apocalypsenow:horde_3",
    "apocalypsenow:horde_4",
    "zombie_extreme:boomer",
    "apocalypsenow:horde_5",
    "apocalypsenow:horde_1",
    "faded_conquest_2:sensoreffect",
    "extinction:soldier_clicker",
    "minecraft:wandering_trader",
    "born_in_chaos_v1:glutton_fish",
    "zombiesmore:boomer_zombie",
    "eeeabsmobs:corpse",
    "extinction:patient_zero",
    "faded_conquest_2:puny_juggernaut",
    "faded_conquest_2:cube_of_calamity",
    "born_in_chaos_v1:corpse_fish",
    "legendary_monsters:skeloraptor",
    "eeeabsmobs:immortal_shaman",
    "born_in_chaos_v1:supreme_bonescaller_stage_2",
    "zombiesmore:cursed_head",
    "legendary_monsters:bomber",
    "extinction:patient_zero_i",
    "cataclysm:netherite_monstrosity",
    "mutantmonsters:mutant_zombie",
    "extinction:infected_hazmat",
    "cataclysm:wadjet",
    "zombiesmore:tank_zombie",
    "mowziesmobs:umvuthana_raptor",
    "apocalypsenow:soldiers",
    "zombie_island:shambler",
    "faded_conquest_2:vfx_purple_aura",
    "faded_conquest_2:blocknight_servant",
    "graveyard:wraith",
    "minecraft:pufferfish",
    "born_in_chaos_v1:bone_imp",
    "minecraft:fox",
    "born_in_chaos_v1:nightmare_stalker",
    "eeeabsmobs:corpse_to_player",
    "born_in_chaos_v1:firelight",
    "mowziesmobs:umvuthana_crane",
    "cataclysm:koboleton",
    "eeeabsmobs:nameless_guardian",
    "minecraft:chicken",
    "born_in_chaos_v1:mr_pumpkin_controlled",
    "minecraft:zombie",
    "graveyard:acolyte",
    "faded_conquest_2:dormant_cube",
    "born_in_chaos_v1:krampus",
    "born_in_chaos_v1:siamese_skeletons",
    "born_in_chaos_v1:lord_pumpkinhead",
    "born_in_chaos_v1:zombie_lumberjack",
    "apocalypsenow:looter_3",
    "apocalypsenow:looter_4",
    "extinction:mercenary",
    "apocalypsenow:looter_5",
    "cataclysm:elite_draugr",
    "zombie_island:hazmat_walker",
    "apocalypsenow:looter_1",
    "minecraft:hoglin",
    "apocalypsenow:looter_2",
    "born_in_chaos_v1:lords_felsteed",
    "legendary_monsters:warped_fungussus",
    "cataclysm:deepling_angler",
    "faded_conquest_2:blocknight_leaper",
    "cataclysm:draugr",
    "apocalypsenow:walker_3",
    "minecraft:polar_bear",
    "apocalypsenow:walker_2",
    "apocalypsenow:walker_5",
    "apocalypsenow:walker_4",
    "minecraft:zombified_piglin",
    "apocalypsenow:walker_1",
    "minecraft:turtle",
    "apocalypsenow:walker_7",
    "minecraft:sheep",
    "apocalypsenow:walker_6",
    "apocalypsenow:walker_9",
    "apocalypsenow:walker_8",
    "zombie_island:walker",
    "born_in_chaos_v1:lord_pumpkinhead_head",
    "faded_conquest_2:blocknight_paladin",
    "graveyard:ghoul",
    "faded_conquest_2:lichspell",
    "born_in_chaos_v1:zombie_fisherman",
    "zombie_extreme:assasin_black_ops",
    "eeeabsmobs:corpse_villager",
    "born_in_chaos_v1:lord_pumpkinhead_withouta_horse",
    "legendary_monsters:frostbitten_golem",
    "faded_conquest_2:mimic",
    "born_in_chaos_v1:controlled_baby_skeleton",
    "extinction:goon",
    "born_in_chaos_v1:fallen_chaos_knight",
    "minecraft:ravager",
    "cataclysm:old_netherite_monstrosity",
    "zombie_extreme:runner",
    "faded_conquest_2:vessel_sword",
    "eeeabsmobs:guling_sentinel_heavy",
    "born_in_chaos_v1:door_knight_not_despawn",
    "eeeabsmobs:tester",
    "born_in_chaos_v1:spirit_guide",
    "extinction:boomer",
    "born_in_chaos_v1:dread_hound_not_despawn",
    "born_in_chaos_v1:riding_lords_felsteed",
    "born_in_chaos_v1:zombie_clown_not_despawn",
    "mowziesmobs:umvuthana_follower_raptor",
    "cataclysm:ender_golem",
    "zombie_island:riot_gear_walker",
    "faded_conquest_2:binded_cube",
    "faded_conquest_2:blocknight_longarm",
    "faded_conquest_2:ttphase_2",
    "legendary_monsters:cloud_golem",
    "born_in_chaos_v1:spiritof_chaos",
    "extinction:infected_mutated",
    "born_in_chaos_v1:sir_pumpkinhead",
    "minecraft:bat",
    "cataclysm:netherite_ministrosity",
    "born_in_chaos_v1:bloody_gadfly",
    "legendary_monsters:knights_armor",
    "faded_conquest_2:agdunegon",
    "apocalypsenow:runner_39",
    "apocalypsenow:runner_38",
    "apocalypsenow:runner_37",
    "zombie_island:caustic_x_walker",
    "born_in_chaos_v1:skeleton_thrasher",
    "zombie_island:runner",
    "apocalypsenow:runner_36",
    "born_in_chaos_v1:decrepit_skeleton",
    "legendary_monsters:withered_abomination",
    "apocalypsenow:runner_35",
    "apocalypsenow:runner_34",
    "apocalypsenow:crawler_3",
    "born_in_chaos_v1:controlled_spiritual_assistant",
    "apocalypsenow:survivor_10",
    "apocalypsenow:crawler_2",
    "apocalypsenow:crawler_4",
    "apocalypsenow:crawler_1",
    "born_in_chaos_v1:bonescaller_not_despawn",
    "apocalypsenow:cockroach",
    "extinction:stalker_ii",
    "apocalypsenow:runner_49",
    "born_in_chaos_v1:baby_skeleton",
    "zombie_extreme:fetus",
    "apocalypsenow:runner_48",
    "born_in_chaos_v1:lifestealer_true_form",
    "cataclysm:deepling",
    "apocalypsenow:runner_43",
    "apocalypsenow:runner_42",
    "apocalypsenow:runner_41",
    "faded_conquest_2:pbprefight",
    "apocalypsenow:runner_40",
    "apocalypsenow:runner_47",
    "apocalypsenow:runner_46",
    "born_in_chaos_v1:thornshell_crab",
    "zombie_extreme:zero_patient",
    "apocalypsenow:runner_45",
    "apocalypsenow:runner_44",
    "cataclysm:ancient_remnant",
    "minecraft:cat",
    "apocalypsenow:runner_50",
    "faded_conquest_2:pbdowned",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "faded_conquest_2:vfx_maiasma",
    "faded_conquest_2:summoned_creeper",
    "zombie_extreme:chainsaw",
    "faded_conquest_2:terrible_ten",
    "apocalypsenow:runner_54",
    "apocalypsenow:runner_53",
    "apocalypsenow:runner_52",
    "minecraft:panda",
    "minecraft:zombie_villager",
    "apocalypsenow:runner_51",
    "zombie_extreme:crawler",
    "apocalypsenow:runner_57",
    "apocalypsenow:runner_56",
    "apocalypsenow:runner_55",
    "born_in_chaos_v1:dire_hound_leader",
    "zombie_extreme:demolisher",
    "minecraft:giant",
    "faded_conquest_2:radiance_guardian",
    "mowziesmobs:lantern",
    "zombie_extreme:infected",
    "legendary_monsters:dark_cloud_golem",
    "cataclysm:amethyst_crab",
    "born_in_chaos_v1:maggot",
    "legendary_monsters:mossy_golem",
    "faded_conquest_2:infested",
    "zombie_extreme:parasite",
    "zombie_extreme:infected_juggernaut",
    "cataclysm:ancient_ancient_remnant",
    "minecraft:husk",
    "eeeabsmobs:immortal",
    "extinction:infected_riot_gear",
    "born_in_chaos_v1:firelight_not_despawn",
    "born_in_chaos_v1:baby_spider_controlled",
    "eeeabsmobs:immortal_golem",
    "eeeabsmobs:immortal_knight",
    "born_in_chaos_v1:door_knight",
    "mowziesmobs:umvuthana",
    "legendary_monsters:haunted_guard",
    "minecraft:donkey",
    "born_in_chaos_v1:felsteed",
    "born_in_chaos_v1:spirit_guide_assistant",
    "born_in_chaos_v1:baby_skeleton_minion",
    "mowziesmobs:umvuthana_crane_player",
    "cataclysm:ignited_berserker",
    "mutantmonsters:mutant_skeleton",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "extinction:traveler",
    "cataclysm:the_baby_leviathan",
    "cataclysm:deepling_brute",
    "apocalypsenow:military_medic",
    "born_in_chaos_v1:pumpkin_spirit",
    "eeeabsmobs:guling_sentinel",
    "born_in_chaos_v1:mr_pumpkin",
    "extinction:soldier",
    "zombie_island:shocking_walker",
    "graveyard:nameless_hanged",
    "born_in_chaos_v1:infernal_spirit",
    "zombie_extreme:infected_police",
    "faded_conquest_2:calamitycagebreak",
    "born_in_chaos_v1:phantom_creeper",
    "eeeabsmobs:immortal_executioner",
    "faded_conquest_2:toxicrow",
    "born_in_chaos_v1:sir_pumpkinhead_without_horse",
    "zombiesmore:boomer_charged",
    "faded_conquest_2:sentry",
    "minecraft:parrot",
    "zombie_extreme:inflated",
    "eeeabsmobs:immortal_skeleton",
    "cataclysm:the_watcher",
    "zombie_island:incendiary_walker",
    "minecraft:frog",
    "legendary_monsters:guard",
    "zombie_extreme:clicker",
    "mutantmonsters:mutant_creeper",
    "faded_conquest_2:meteor",
    "zombie_island:runner_2",
    "zombie_island:runner_1",
    "zombie_extreme:explosive_infected",
    "minecraft:mule",
    "zombie_island:shambler_4",
    "zombie_island:shambler_3",
    "minecraft:vindicator",
    "zombie_island:burning_walker",
    "zombie_island:runner_4",
    "zombie_island:runner_3",
    "minecraft:evoker",
    "zombie_island:shambler_2",
    "born_in_chaos_v1:barrel_zombie",
    "zombie_island:shambler_1",
    "zombie_extreme:infected_hazmat",
    "cataclysm:nameless_sorcerer",
    "cataclysm:endermaptera",
    "graveyard:ghouling",
    "cataclysm:lionfish",
    "born_in_chaos_v1:decaying_zombie",
    "born_in_chaos_v1:corpse_fly",
    "legendary_monsters:spiky_bug",
    "cataclysm:coralssus",
    "graveyard:revenant",
    "faded_conquest_2:vessel_shield",
    "zombie_extreme:ram",
    "graveyard:lich",
    "eeeabsmobs:corpse_warlock",
    "faded_conquest_2:demon",
    "apocalypsenow:walker_29",
    "graveyard:corrupted_pillager",
    "apocalypsenow:walker_28",
    "apocalypsenow:walker_27",
    "apocalypsenow:walker_26",
    "apocalypsenow:walker_25",
    "apocalypsenow:walker_24",
    "apocalypsenow:walker_23",
    "apocalypsenow:walker_22",
    "apocalypsenow:walker_21",
    "apocalypsenow:walker_20",
    "cataclysm:the_harbinger",
    "faded_conquest_2:whirlwind",
    "zombiesmore:cursed_zombie",
    "born_in_chaos_v1:phantom_bomb_entity",
    "mowziesmobs:bluff",
    "mowziesmobs:grottol",
    "faded_conquest_2:faded_kingp_2",
    "minecraft:pig",
    "born_in_chaos_v1:restless_spirit",
    "legendary_monsters:hovering_hurricane",
    "extinction:infected_bear",
    "legendary_monsters:dune_sentinel",
    "mowziesmobs:baby_foliaath",
    "apocalypsenow:walker_33",
    "apocalypsenow:walker_32",
    "born_in_chaos_v1:swarmer",
    "apocalypsenow:walker_31",
    "apocalypsenow:walker_30",
    "minecraft:goat",
    "mutantmonsters:mutant_enderman",
    "faded_conquest_2:blocknightfist",
    "faded_conquest_2:the_plauge_bringerp_2",
    "minecraft:cod",
    "zombie_extreme:rat_king",
    "born_in_chaos_v1:pumpkinhead",
    "legendary_monsters:posessed_paladin",
    "mutantmonsters:spider_pig",
    "extinction:hunter",
    "minecraft:cow",
    "mowziesmobs:umvuthi",
    "born_in_chaos_v1:scarlet_persecutor",
    "born_in_chaos_v1:phantom_creeper_copy",
    "apocalypsenow:survivor_5",
    "apocalypsenow:survivor_4",
    "apocalypsenow:survivor_3",
    "apocalypsenow:survivor_2",
    "apocalypsenow:survivor_1",
    "faded_conquest_2:poison_spike_b",
    "minecraft:salmon",
    "cataclysm:ignis",
    "apocalypsenow:walker_19",
    "mowziesmobs:naga",
    "apocalypsenow:walker_18",
    "born_in_chaos_v1:seared_spirit",
    "apocalypsenow:walker_17",
    "apocalypsenow:survivor_9",
    "apocalypsenow:walker_16",
    "apocalypsenow:survivor_8",
    "apocalypsenow:walker_15",
    "apocalypsenow:survivor_7",
    "apocalypsenow:walker_14",
    "extinction:parasite",
    "apocalypsenow:survivor_6",
    "apocalypsenow:walker_13",
    "born_in_chaos_v1:dark_vortex",
    "apocalypsenow:walker_12",
    "apocalypsenow:walker_11",
    "apocalypsenow:walker_10",
    "extinction:stalker",
    "mowziesmobs:ferrous_wroughtnaut",
    "born_in_chaos_v1:zombie_clown",
    "minecraft:rabbit",
    "minecraft:pillager",
    "born_in_chaos_v1:decaying_zombie_not_despawn",
    "minecraft:zoglin",
    "born_in_chaos_v1:zombie_bruiser",
    "faded_conquest_2:the_plauge_bringer",
    "legendary_monsters:chorusling",
    "born_in_chaos_v1:krampus_henchman",
    "born_in_chaos_v1:lord_the_headless",
    "legendary_monsters:ancient_guardian",
    "faded_conquest_2:aero_guardian",
    "zombie_extreme:night_hunter",
    "born_in_chaos_v1:diamond_termite",
    "cataclysm:kobolediator",
    "faded_conquest_2:blocknight_heavyman",
    "extinction:fallen_survivor",
    "cataclysm:deepling_priest",
    "faded_conquest_2:heiroglyph_room",
    "faded_conquest_2:calamity_beam",
    "faded_conquest_2:summoned_spider",
    "mutantmonsters:endersoul_clone",
    "legendary_monsters:skeletosaurus",
    "minecraft:piglin",
    "legendary_monsters:lava_eater",
    "faded_conquest_2:fcdungeon",
    "born_in_chaos_v1:sir_the_headless",
    "faded_conquest_2:blocknight_fool",
    "cataclysm:ignited_revenant",
    "graveyard:corrupted_vindicator",
    "extinction:infected_soldier",
    "apocalypsenow:military_02",
    "apocalypsenow:military_01",
    "minecraft:sniffer",
    "faded_conquest_2:vessel_spawn",
    "faded_conquest_2:mr_void",
    "faded_conquest_2:doomharbor_lich",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "cataclysm:royal_draugr",
    "apocalypsenow:cannibal",
    "zombie_extreme:military",
    "born_in_chaos_v1:bonescaller",
    "zombiesmore:crawler",
    "legendary_monsters:endersent",
    "cataclysm:aptrgangr",
    "born_in_chaos_v1:missioner",
    "minecraft:ocelot",
    "mowziesmobs:umvuthana_follower_player",
    "cataclysm:modern_remnant",
    "born_in_chaos_v1:supreme_bonescaller_not_despawn",
    "minecraft:wolf",
    "extinction:runner_ii"
]
